### ISSUE TITLE
Unhandled rejection SequelizeDatabaseError: type "jsonb" does not exist

### ISSUE THREAD

**Issue by sdaban** [StetSolutions/pean#30]
Hi,

this is what I get, when running `grunt`.
Can you please help me?

Thanks!

```
ubuntu@ip-172-31-17-237:~/peanjs$ grunt
Running "env:dev" (env) task

Running "sass:dist" (sass) task

Running "less:dist" (less) task
>> 2 stylesheets created.

Running "jshint:all" (jshint) task
>> 114 files lint free.

Running "eslint:target" (eslint) task

Running "csslint:all" (csslint) task
>> 3 files lint free.

Running "mkdir:upload" task

Running "copy:localConfig" (copy) task


Running "concurrent:default" (concurrent) task
    Running "nodemon:dev" (nodemon) task
    Running "watch" task
    Waiting...
    [nodemon] 1.11.0
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: gruntfile.js modules/*/server/views/*.html server.js config/**/*.js modules/*/server/**/*.js modules/*/server/config/*.js
    [nodemon] starting `node --debug server.js`
    Debugger listening on port 5858
    
    
    Unhandled rejection SequelizeDatabaseError: type "jsonb" does not exist
        at Query.formatError (/home/ubuntu/peanjs/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
        at null.<anonymous> (/home/ubuntu/peanjs/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
        at emitOne (events.js:90:13)
        at emit (events.js:182:7)
        at Query.handleError (/home/ubuntu/peanjs/node_modules/pg/lib/query.js:108:8)
        at null.<anonymous> (/home/ubuntu/peanjs/node_modules/pg/lib/client.js:171:26)
        at emitOne (events.js:90:13)
        at emit (events.js:182:7)
        at Socket.<anonymous> (/home/ubuntu/peanjs/node_modules/pg/lib/connection.js:109:12)
        at emitOne (events.js:90:13)
        at Socket.emit (events.js:182:7)
        at readableAddChunk (_stream_readable.js:153:18)
        at Socket.Readable.push (_stream_readable.js:111:10)
        at TCP.onread (net.js:534:20)
    From previous event:
        at Query.run (/home/ubuntu/peanjs/node_modules/sequelize/lib/dialects/postgres/query.js:74:17)
        at /home/ubuntu/peanjs/node_modules/sequelize/lib/sequelize.js:849:20
        at /home/ubuntu/peanjs/node_modules/retry-as-promised/index.js:40:21
        at retryAsPromised (/home/ubuntu/peanjs/node_modules/retry-as-promised/index.js:30:10)
        at null.<anonymous> (/home/ubuntu/peanjs/node_modules/sequelize/lib/sequelize.js:848:12)
    From previous event:
        at Promise.then (/home/ubuntu/peanjs/node_modules/sequelize/lib/promise.js:21:17)
        at Model.sync (/home/ubuntu/peanjs/node_modules/sequelize/lib/model.js:993:6)
        at /home/ubuntu/peanjs/node_modules/sequelize/lib/sequelize.js:1014:20
    From previous event:
        at Function.each (/home/ubuntu/peanjs/node_modules/sequelize/lib/promise.js:21:17)
        at /home/ubuntu/peanjs/node_modules/sequelize/lib/sequelize.js:1013:20
        at tryOnImmediate (timers.js:534:15)
        at processImmediate [as _immediateCallback] (timers.js:514:5)
    From previous event:
        at Promise.then (/home/ubuntu/peanjs/node_modules/sequelize/lib/promise.js:21:17)
        at Sequelize.sync (/home/ubuntu/peanjs/node_modules/sequelize/lib/sequelize.js:1000:6)
        at Object.init (/home/ubuntu/peanjs/config/lib/app.js:22:4)
        at Object.start (/home/ubuntu/peanjs/config/lib/app.js:50:9)
        at Object.<anonymous> (/home/ubuntu/peanjs/server.js:9:18)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:148:18)
        at node.js:405:3
```

**Comment by vaucouleur** [comment]
@sdaban jsonb support was introduced in postgres 9.4 with further support in 9.5, check the following links. What postgres version are you using ?

https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.4#JSONB_Binary_JSON_storage

https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#JSONB-modifying_operators_and_functions

**Comment by sdaban** [comment]
Hi @vaucouleur !
Thank you very much for your quick response.
I did use postgres 9.4.
Now I upgraded Ubuntu to 16.04 and also updated postegres to 9.5.5.
However, the problem is still existing.
Any other suggestions?

Thanks,
Shahab
